//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptPets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adoption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adoption()
        {
            this.updates = new HashSet<update>();
        }
    
        public int id { get; set; }
        public int id_request { get; set; }
        public int id_animal { get; set; }
        public int id_previous_owner { get; set; }
        public int id_new_owner { get; set; }
        public System.DateTime adoption_date { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual request request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<update> updates { get; set; }
    }
}
