//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptPets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class animal_vaccines
    {
        public int id_animal { get; set; }
        public int id_vaccine { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Vaccine Vaccine { get; set; }
    }
}
