//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptPets.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class adoptpetsEntities : DbContext
    {
        public adoptpetsEntities()
            : base("name=adoptpetsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adoption> Adoptions { get; set; }
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<animal_conditions> animal_conditions { get; set; }
        public virtual DbSet<animal_vaccines> animal_vaccines { get; set; }
        public virtual DbSet<announcement> announcements { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Condition> Conditions { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<image> images { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<request> requests { get; set; }
        public virtual DbSet<Residence> Residences { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Species> Species { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<update> updates { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<users_jobs> users_jobs { get; set; }
        public virtual DbSet<Vaccine> Vaccines { get; set; }
    }
}
