//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoptPets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public request()
        {
            this.Adoptions = new HashSet<Adoption>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_ann { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<System.DateTime> dateReq { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adoption> Adoptions { get; set; }
        public virtual announcement announcement { get; set; }
        public virtual status status { get; set; }
        public virtual User User { get; set; }
    }
}
